### PR TITLE
Add heal context

### PR DESCRIPTION
**Pull request by n0mn0m**
- Setup basic heal context for tycho
- Bump version
- Tested with test pypi and appstore

#ref helxplatform/development#671

### CODE REVIEW

**Review by stevencox — APPROVED** [review]

**Comment by n0mn0m** [comment]
@ismagilani @muralikarthikk do we normally wait till we merge `develop` to `master` to push a new pypi package? [Appstore](https://github.com/helxplatform/appstore/pull/91/files) will need the `1.0.13` version update from pypi before it merges.

**Comment by stevencox** [comment]
@cschreep - do you have written thoughts on the relationship envisioned between develop/master and publishing to pypi?

**Comment by cschreep** [comment]
I generally like [gitflow](https://nvie.com/posts/a-successful-git-branching-model/) in which case the publishing would happen together with tagging master with the new version

**Comment by ismagilani** [comment]
Thanks @cschreep I will read up on gitflow. 

@n0mn0m It is my understanding that currently tycho automated build is not publishing to pypi.  @muralikarthikk and I followed a manual process earlier this week for development, testing, and deployment when changes were required in both tycho and appstore:

1. Code in your feature branch 
2. Push tycho changes in feature branch to **testpypi**
3. Use testpypi tycho package for testing appstore in your namespace
4. PR and push to develop for tycho first, push tycho package to **pypi**
5. PR and push to develop for appstore with tycho version from 4
6. Repeat 4 and 5 with develop->master 

@muralikarthikk please correct me if I got something wrong.

**Comment by n0mn0m** [comment]
Got it. I've done steps 1-3.

Are we doing something special to push tycho to pypi twice (step 4 and 6)? I didn't think we could push the same package version, and I'm not sure what the benefit would be since the merge from `develop` -> `master` shouldn't contain any code not already pushed in step 4. I think I may be missing some context in that 4 -> 6 flow, or we just push it once in step 4, and it's available for the appstore merge from `develop` -> `master` already.

**Comment by ismagilani** [comment]
@n0mn0m great observation but I think the only thing is in step 6, we publish an image built from master?

So should we publish to pypi once with content from tycho master and then use it feature->develop and develop->master?

@muralikarthikk

**Comment by n0mn0m** [comment]
IMO and related to gitflow I think publishing to `master` is when we want to publish to pypi.

**Pull request merged**
