### PR TITLE
Augment proxy rewrite

### PR DESCRIPTION
**Pull request by waTeim**
Add to tycho the capability of setting the rewrite target to tycho while preserving backwards compatibility.

old:
   
    proxy-rewrite-rule: boolean

new:

    proxy-rewrite:
      enabled: boolean
      target: string

In the new implementation, `proxy-rewrite-rule` is still allowed, which is used to set `proxy-rewrite.enabled` in this instance **target** defaults to **None**.  If a value of None is encountered, then the old rules apply.  Both `enabled` and `proxy-rewrite-rule` default to **False**.

Additionally, if `target` is not **None** then an additional ambassador directive is included to recover the original URL.

    add_response_headers:
        X-Original-Path: <same as the value of prefix>

### CODE REVIEW

**Comment by frostyfan109** [comment]
Do we know what `proxy_rewrite_rule` is supposed to do currently (like before this change)? I'm still unclear on its purpose.

**Comment by waTeim** [comment]
As am I, GPT claims all it did previously was set rewrite to the same value as prefix which accomplished nothing.

**Comment by frostyfan109** [comment]
I'm pretty sure you said that none of the apps currently (besides RStudio) are using this anyways? So I don't really think there's any reason to hold off on merging. But if that's wrong and apps are using this we should probably figure out what it does.

I know in the tycho code it appears like this rule is completely redundant, so I'm curious why enabling it changed the behavior of RStudio?

**Comment by waTeim** [comment]
It is on for Jupyter, and I did verify that its behavior is unchanged.  I now half-suspect enabling proxy-rewrite-rule for  R last week didn't actually fix R, but something else was going on (which I found out during testing).

**Comment by frostyfan109** [comment]
When I modified the service mapping for RStudio, it affected its behavior? So even if it didn't fix it a couple weeks ago, it still changed something about how Ambassador was proxying its requests, which puzzles me having looked at the Tycho code.

**Comment by waTeim** [comment]
Heisenbug (mild) is what I'm thinking currently.

**Comment by frostyfan109** [comment]
It's not because when I changed the service spec back the behavior went back to expected, so I think it must change something.

**Review by pj-linebaugh — APPROVED** [review]

**Pull request merged**
