### PR TITLE
Use a label selector to identify when ambassador is up in a backwards-compatible way

### PR DESCRIPTION
**Pull request by Hoid**
In old deployments of tycho, the application would check for a namespaced service with the name `ambassador`, and if more than 0 existed it would consider ambassador to be up. The problem with this is that when running multiple ambassadors in one namespace we might call the ambassador deployments different things, like `student-ambassador` and `professor-ambassador` (in the case of Eduhelx). This PR creates a new environment variable for tycho called `AMBASSADOR_SVC_NAME` which pulls in the ambassador service name from the deployment's values file and uses it when calling `list_namespaced_service()`, instead of assuming the name of the service will just be called `ambassador`.

### CODE REVIEW

**Comment by pj-linebaugh** [comment]
If a student-helx tycho finds the professor-helx's ambassador then would it think it's ambassador is running even if the student-helx ambassador is disabled?

**Comment by Hoid** [comment]
> If a student-helx tycho finds the professor-helx's ambassador then would it think it's ambassador is running even if the student-helx ambassador is disabled?

Hmm yes, that's true. I suppose the worst that can come of that scenario is that the application doesn't fail as fast as it could have otherwise. The question is whether that's an acceptable price to pay for not making more drastic changes to tycho. Do you think it's necessary to for example inject the name of the ambassador service we are using into tycho using an environment variable in the chart and use that variable to search for the existing service? Or is this current solution sufficient for now?

**Review by joshua-seals — APPROVED** [review]

**Comment by pj-linebaugh** [comment]
Passing the name of the ambassador service to tycho via an environment variable and have it check for that rather than just "ambassador" seems a good way to go.  That would go along with the spirit of the check.  I also can't remember a time when we deployed helx without an ambassador, so removing all that entirely and assuming ambassador is being used could be a better way to go and remove some unneeded code bloat.  Is the label app=ambassador used for anything else?  If we really want to keep ambassador optional could add an environment variable for tycho like USE_AMBASSADOR and set it's default value to true.  Not sure what tycho would do without ambassador.  So, a few options and like you have it now it will work, just might not work for all situations (like the helx ambassador is disabled for some reason for a helx site, and there's another ambassador that's part of another site running in the same ns).  Have you successfully tested this?  I'm getting to my unknowns here.  I think ambassador checks the services for it's annotations and creates a mapping if it finds one.  How does the ambassador know that the service is really for it's helx website and not another one in the ns?



--

PJ Linebaugh

Cloud and Linux System Administrator

Renaissance Computing Institute (RENCI)

University of North Carolina
***@***.***

RENCI

________________________________

**Comment by joshua-seals** [comment]
I think @pj-linebaugh brings up a good point here about "how 1 ambassador is differentiated from another" and "how tycho indicates it". But seems like this function is just a bool check so I assume there is a way to distinguish 1 instance of ambassador from another and the logic is supported in tycho?

**Comment by Hoid** [comment]
Merging anyways just so tycho is up to date in case we decide to move back

**Pull request merged**
