### PR TITLE
Merge Develop --> Master

### PR DESCRIPTION
**Pull request by muralikarthikk**

### CODE REVIEW

**Comment by stevencox** [comment]
@ismagilani @muralikarthikk didn't you edit out commits to tycho's [metadata loading code](https://github.com/helxplatform/tycho/pull/130/commits/412b648323658d104949ba3857afd1345ae2dbde)? Have those accidentally made their way back in or is this intentional?

**Review by ismagilani — APPROVED** [review]

**Comment by muralikarthikk** [comment]
> @ismagilani @muralikarthikk didn't you edit out commits to tycho's [metadata loading code](https://github.com/helxplatform/tycho/pull/130/commits/412b648323658d104949ba3857afd1345ae2dbde)? Have those accidentally made their way back in or is this intentional?

@stevencox There are few commits that were reverted to original, this is one of it.

**Review by waTeim — APPROVED** [review]
The deployment <- service dependency mod looks good.

**Review by Acharya-Saurya — APPROVED** [review]

**Comment by ismagilani** [comment]
@stevencox, I understand your concern about unintentional commits making it into the develop branch but after careful review of the Files Changed (context.py) in this PR and examining the argus/kstars PR which may have resulted in these commits, I believe what we have in develop for context.py is fine.  @muralikarthikk and @waTeim got on a call and verified as well.  The commits you are referring to above were reverted before they were merged to develop.

**Review by stevencox — APPROVED** [review]

**Pull request merged**
